layout_spectrum: 0.2026529
typography_spectrum: 0.5301965
color:
  saturation: 0.8417232
  lightness: 0.6456515
  brandStrength: 0.7899696
  rhythmicContrast: 0.7210781
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Hackday
